// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMIxAbQSYSId16fKIThWUmu-SYmSydowg',
    appId: '1:794827757760:web:26fc5df1103f48fa4a3525',
    messagingSenderId: '794827757760',
    projectId: 'game-board-9a1f1',
    authDomain: 'game-board-9a1f1.firebaseapp.com',
    storageBucket: 'game-board-9a1f1.firebasestorage.app',
    measurementId: 'G-86S6HJ8JCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1LVfly5wiYHitIfg2bnWcYMieGEuB61U',
    appId: '1:794827757760:android:c8f1d5fb9108f7544a3525',
    messagingSenderId: '794827757760',
    projectId: 'game-board-9a1f1',
    storageBucket: 'game-board-9a1f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRhP94bJ23F7AQ7ZCmPu2fk5ihehK1XIk',
    appId: '1:794827757760:ios:73967fc74fd63e174a3525',
    messagingSenderId: '794827757760',
    projectId: 'game-board-9a1f1',
    storageBucket: 'game-board-9a1f1.firebasestorage.app',
    iosBundleId: 'com.ipssi.gameboard.gameBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRhP94bJ23F7AQ7ZCmPu2fk5ihehK1XIk',
    appId: '1:794827757760:ios:73967fc74fd63e174a3525',
    messagingSenderId: '794827757760',
    projectId: 'game-board-9a1f1',
    storageBucket: 'game-board-9a1f1.firebasestorage.app',
    iosBundleId: 'com.ipssi.gameboard.gameBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMIxAbQSYSId16fKIThWUmu-SYmSydowg',
    appId: '1:794827757760:web:c61fdc5fa4ddd4244a3525',
    messagingSenderId: '794827757760',
    projectId: 'game-board-9a1f1',
    authDomain: 'game-board-9a1f1.firebaseapp.com',
    storageBucket: 'game-board-9a1f1.firebasestorage.app',
    measurementId: 'G-XV2R46YHLH',
  );
}
